export default {
	LOAD_UFO_DATA: "LOAD_UFO_DATA",
	LOAD_UFO_DATA_SUCCESS: "LOAD_UFO_DATA_SUCCESS",
	LOAD_UFO_DATA_FAIL: "LOAD_UFO_DATA_FAIL",
	LOAD_QUAKE_DATA: "LOAD_QUAKE_DATA",
	LOAD_QUAKE_DATA_SUCCESS: "LOAD_QUAKE_DATA_SUCCESS",
	LOAD_QUAKE_DATA_FAIL: "LOAD_QUAKE_DATA_FAIL",
	SET_LOADING_INDICATOR: "SET_LOADING_INDICATOR",
	DECREMENT: "DECREMENT",
	INCREMENT: "INCREMENT",
	FIRE_ASYNC_INCREMENT: "INCREMENT",
	FIRE_ASYNC_DECREMENT: "DECREMENT",
};
