export default {
	LOAD_UFO_DATA: "LOAD_UFO_DATA",
	LOAD_UFO_DATA_SUCCESS: "LOAD_UFO_DATA_SUCCESS",
	LOAD_UFO_DATA_FAILURE: "LOAD_UFO_DATA_FAILURE",
	LOAD_QUAKE_DATA: "LOAD_QUAKE_DATA",
	LOAD_QUAKE_DATA_SUCCESS: "LOAD_QUAKE_DATA_SUCCESS",
	LOAD_QUAKE_DATA_FAILURE: "LOAD_QUAKE_DATA_FAILURE",
	SET_LOADING_INDICATOR: "SET_LOADING_INDICATOR",

	INCREMENT: "INCREMENT",
	DECREMENT: "DECREMENT",
	FIRE_ASYNC_INCREMENT: "FIRE_ASYNC_INCREMENT",
	FIRE_ASYNC_DECREMENT: "FIRE_ASYNC_DECREMENT",
};
